# Generated by Django 3.2.9 on 2021-11-06 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0002_alter_baseblog_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tagname',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Tag Name'),
            preserve_default=False,
        ),
    ]
